### ISSUE TITLE
Tox tests currently don't pass

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/home-assistant#1]
When running tox on my Debian machine I use for development I get an error. What is strange is that when I start hass, the pyhomematic dependency doesn't get installed automatically. The same happens when running tox. There are the final lines of the output:

```bash
...
requirements installed: eventlet==0.19.0,greenlet==0.4.9,homeassistant==0.22.0.dev0,Jinja2==2.8,MarkupSafe==0.23,pytz==2016.4,PyYAML==3.11,requests==2.10.0,voluptuous==0.8.9
requirements runtests: PYTHONHASHSEED='1785069134'
requirements runtests: commands[0] | python script/gen_requirements_all.py validate
Traceback (most recent call last):
  File "script/gen_requirements_all.py", line 132, in <module>
    main()
  File "script/gen_requirements_all.py", line 116, in main
    data = gather_modules()
  File "script/gen_requirements_all.py", line 58, in gather_modules
    for package in sorted(explore_module('homeassistant.components', True)):
  File "script/gen_requirements_all.py", line 33, in explore_module
    found.extend(explore_module(name, False))
  File "script/gen_requirements_all.py", line 22, in explore_module
    module = importlib.import_module(package)
  File "/root/src/ha/home-assistant/.tox/requirements/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/root/src/ha/home-assistant/homeassistant/components/homematic.py", line 16, in <module>
    import pyhomematic
ImportError: No module named 'pyhomematic'
ERROR: InvocationError: '/root/src/ha/home-assistant/.tox/requirements/bin/python script/gen_requirements_all.py validate'
_____________________________________________ summary ______________________________________________
ERROR:   py34: could not install deps [-r/root/src/ha/home-assistant/requirements_all.txt, -r/root/src/ha/home-assistant/requirements_test.txt]; v = InvocationError('/root/src/ha/home-assistant/.tox/py34/bin/pip install -r/root/src/ha/home-assistant/requirements_all.txt -r/root/src/ha/home-assistant/requirements_test.txt (see /root/src/ha/home-assistant/.tox/py34/log/py34-1.log)', 1)
SKIPPED:  py35: InterpreterNotFound: python3.5
ERROR:   lint: could not install deps [-r/root/src/ha/home-assistant/requirements_all.txt, -r/root/src/ha/home-assistant/requirements_test.txt]; v = InvocationError('/root/src/ha/home-assistant/.tox/lint/bin/pip install -r/root/src/ha/home-assistant/requirements_all.txt -r/root/src/ha/home-assistant/requirements_test.txt (see /root/src/ha/home-assistant/.tox/lint/log/lint-1.log)', 1)
ERROR:   requirements: commands failed
```

**Comment by danielperna84** [comment]
Deleted requirements_all.txt provided by repo and now everything works.

**Comment by danielperna84** [comment]
Well, I thought that file would be recreated. Turns it that's not the case.

**Comment by danielperna84** [comment]
Added pylint-comments to suppress some warnings and made some minor changes suggested by lint.
lint-tests now pass, except for rollershutter-platforms that don't know about init.position.

**Comment by danielperna84** [comment]
```tox -e lint``` on Windows 10 results in the following output:
```
...
lint runtests: PYTHONHASHSEED='720'
lint runtests: commands[0] | flake8
.\homeassistant\components\homematic.py:22:1: E402 module level import not at top of file
ERROR: InvocationError: 'C:\\Users\\...\\home-assistant\\.tox\\lint\\Scripts\\flake8.EXE'
lint runtests: commands[1] | pylint homeassistant
************* Module homeassistant.__main__
E:145,10: Module 'os' has no 'fork' member (no-member)
E:150, 4: Module 'os' has no 'setsid' member (no-member)
E:153,10: Module 'os' has no 'fork' member (no-member)
E:246, 4: Unable to import 'fcntl' (import-error)
E:337,17: Module 'os' has no 'sysconf' member (no-member)
************* Module homeassistant.components.notify.syslog
E: 23, 4: Unable to import 'syslog' (import-error)
E: 81, 8: Unable to import 'syslog' (import-error)
ERROR: InvocationError: 'C:\\Users\\...\\home-assistant\\.tox\\lint\\Scripts\\pylint.EXE homeassistant'
lint runtests: commands[2] | pydocstyle homeassistant tests
___________________________________ summary ___________________________________
ERROR:   lint: commands failed
´´´

The import error can't be circumvented since it has to be done that way.
The rest is not related to homematic.

**Comment by danielperna84** [comment]
Only thing missing now probably is the failing import of pyhomematic.

**Comment by pvizeli** [comment]
I've found the trouble:

> test@test-node:~/home-assistant$ tox -e requirements
> GLOB sdist-make: /home/test/home-assistant/setup.py
> requirements create: /home/test/home-assistant/.tox/requirements
> requirements inst: /home/test/home-assistant/.tox/dist/homeassistant-0.22.0.dev0.zip
> requirements installed: eventlet==0.19.0,greenlet==0.4.10,homeassistant==0.22.0.dev0,Jinja2==2.8,MarkupSafe==0.23,pytz==2016.4,PyYAML==3.11,requests==2.10.0,voluptuous==0.8.9
> requirements runtests: PYTHONHASHSEED='1056347049'
> requirements runtests: commands[0] | python script/gen_requirements_all.py validate
> Traceback (most recent call last):
>   File "script/gen_requirements_all.py", line 132, in <module>
>     main()
>   File "script/gen_requirements_all.py", line 116, in main
>     data = gather_modules()
>   File "script/gen_requirements_all.py", line 58, in gather_modules
>     for package in sorted(explore_module('homeassistant.components', True)):
>   File "script/gen_requirements_all.py", line 33, in explore_module
>     found.extend(explore_module(name, False))
>   File "script/gen_requirements_all.py", line 22, in explore_module
>     module = importlib.import_module(package)
>   File "/home/test/home-assistant/.tox/requirements/lib/python3.4/importlib/__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1129, in _exec
>   File "<frozen importlib._bootstrap>", line 1471, in exec_module
>   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
>   File "/home/test/home-assistant/homeassistant/components/homematic.py", line 29, in <module>
>     import pyhomematic as HOMEMATIC
> ImportError: No module named 'pyhomematic'
> ERROR: InvocationError: '/home/test/home-assistant/.tox/requirements/bin/python script/gen_requirements_all.py validate'
> ___________________________________ summary ____________________________________
> ERROR:   requirements: commands failed
