### ISSUE TITLE
homematic_binary_sensor: Device Setup fails if param is empty

### ISSUE THREAD

**Issue by Koshu** [danielperna84/home-assistant#13]
Encountered a bug in the binary_sensor code. If no "param" is specified in the configuration device setup fails and the device marked as unavailable in the webinterface:

`WARNING:homeassistant.components.binary_sensor.homematic:Schlafzimmer Oben have multible binary params. It use all binary nodes as one. Possible param values: {'PRESS_LONG': 'c', 'PRESS_SHORT': 'c'}
ERROR:homeassistant.components.homematic:Failed to setup device MEQ0397491: 'in <string>' requires string as left operand, not NoneType`

My Config:
[binary_sensors.txt](https://github.com/danielperna84/home-assistant/files/331871/binary_sensors.txt)

**Comment by danielperna84** [comment]
This only applies to devices with multiple channels and event-types, such as the button. Without the param it is not known which events should be captured. A Shutter-Contact with only channel and one relevant event doesn't require the param.
This will be covered in the documentation.

**Comment by Koshu** [comment]
Then the warning might be a bit misleading. I thought that "It use all binary nodes as one" means that if you do not specify a "param" the turn_on/turn_off events are fired regardless which type (PRESS_SHORT...) it is. Especially since it is marked as optional in the docs.

Also, should it throw an error like that ('in <string>' requires string as left operand, not NoneType)? No biggie, but didn't look like clean exception handling.

Testing the rest right now. Looks fine so far. Also, nice to see that you can use the long press buttons again. 

So, thanks for all the work.

**Comment by danielperna84** [comment]
It was actually bug. It is now fixed.
You can get the latest state from pvizelis repo here: https://github.com/pvizeli/home-assistant/tree/Homematic
